title: Microservicio del bot conversacional
description: Documentacion del microservicio que gestiona el bot conversacional de "SocioUnido"
theme: just-the-docs

url: "https://trabajoprofesional-aggz.github.io"

baseurl: "/microservicio-bot-conversacional"
